apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone:1.0.0-16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone:1.0.0-16
  template:
    metadata:
      labels:
        app: reddit-clone:1.0.0-16
    spec:
      containers:
        - name: reddit-clone:1.0.0-16
          image: mukeshr29/reddit-clone:1.0.0-16
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000